# Generated by Django 3.1.2 on 2020-10-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='not defined', max_length=100),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
